### ISSUE TITLE
【已解决】安装完之后重启ComfyUI一直卡在这里是什么意思？

### ISSUE THREAD

**Issue by shao-ming** [THtianhao/ComfyUI-FaceChain#12]
ComfyUI-FaceChain : ### : Check dependencies
ComfyUI-FaceChain : E:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FaceChain\requirements.txt
ComfyUI-FaceChain : aliyun-python-sdk-core-v3==2.13.10

ComfyUI-FaceChain : python-slugify==8.0.1

ComfyUI-FaceChain : onnxruntime-gpu

ComfyUI-FaceChain : timm

ComfyUI-FaceChain : modelscope

ComfyUI-FaceChain : controlnet_aux==0.0.6

ComfyUI-FaceChain : install controlnet_aux==0.0.6

ComfyUI-FaceChain : EXECUTE: ['E:\\AI\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-s', '-m', 'pip', 'install', '-q', 'controlnet_aux==0.0.6\n'] in 'E:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FaceChain'
ComfyUI-FaceChain : mmdet==2.26.0

ComfyUI-FaceChain : mediapipe

ComfyUI-FaceChain : transformers

ComfyUI-FaceChain : insightface

ComfyUI-FaceChain : sentencepiece

ComfyUI-FaceChain : EXECUTE: ['E:\\AI\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-s', '-m', 'pip', 'install', '-q', '-U', 'openmim'] in 'E:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FaceChain'
ComfyUI-FaceChain : EXECUTE: ['E:\\AI\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-s', '-m', 'mim', 'install', '-q', 'mmcv-full'] in 'E:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FaceChain'

**Comment by shao-ming** [comment]
安装pip install controlnet-aux 解决

**Comment by THtianhao** [comment]
ok
