### ISSUE TITLE
facechain使用

### ISSUE THREAD

**Issue by yuanhuikai** [THtianhao/ComfyUI-FaceChain#5]
针对 现有的 图片 人物脸，进行 高兴、伤心。  这个用其他workflow来解决了，想用facechain的workflow 实现 自动 定位 脸部， 后续自动拼接到现有图片上， 我添加完以后，爆显存了，是我使用的不合理吧。 
![image](https://github.com/THtianhao/ComfyUI-FaceChain/assets/7391649/1b52fa00-d998-42ab-a2fe-af0c840251d3)
求大佬指点

**Comment by THtianhao** [comment]
显卡可能不太够用

**Comment by wangfeng35** [comment]
> 显卡可能不太够用

这个得多大显卡才能用啊 16G起步？

**Comment by THtianhao** [comment]
差不多吧
