### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by Elminsst** [THtianhao/ComfyUI-FaceChain#6]
每次启动都回执行一下命令：
![image](https://github.com/THtianhao/ComfyUI-FaceChain/assets/130235860/3728a1e2-a4c2-4bd9-a3be-c2b0ea8b0fa5)
然后会卡很久
最后显示
![image](https://github.com/THtianhao/ComfyUI-FaceChain/assets/130235860/e63d53b4-1325-491f-a1f7-0099a63dcd64)
但是，节点确实加载成功了
![image](https://github.com/THtianhao/ComfyUI-FaceChain/assets/130235860/5cdc522c-cea6-4dc6-9ff2-76e5755a6ed3)
这个应该怎么ch处理？？手动安装mmcv-full可以解决吗？

**Comment by Elminsst** [comment]
另：加群的二维码过期了...

**Comment by THtianhao** [comment]
好嘞二维码已经更新
